### ISSUE TITLE
Unable to create OneToOne Relationships

### ISSUE THREAD

**Issue by GromHub** [jhipster/jhipster-dotnetcore#1334]
##### **Overview of the issue**

Hello
I successfully generated my jhipster.net application with the blueprint and created several entities with jhipster manual creation and jdl import.
I was also able to create OneToMany, ManyToOne and ManyToMany relationships with jdl import, but was unable to create any OneToOne relationships : each time, the process fails with the following error:

```
Error running generator entities: TypeError: Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at toNoCase (C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\node_modules\to-no-case\index.js:28:17)
    at toSpaceCase (C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\node_modules\to-space-case\index.js:18:10)
    at toPascalCase (C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\node_modules\to-pascal-case\index.js:18:10)
    at C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\generators\entity\index.js:154:78
    at Array.forEach (<anonymous>)
    at module.exports.preparingDotnetRelationships (C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\generators\entity\index.js:136:39)
    at Object.<anonymous> (C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1097:23)
    at C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\node_modules\run-async\index.js:49:25
    at new Promise (<anonymous>)
    at C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\node_modules\run-async\index.js:26:19
```

Here is the Relationship i'm trying to create (it was taken from the sample app):

```
entity Region {
	regionName String
}

entity Country {
	countryName String
}

relationship OneToOne {
	Country{region} to Region
}
```

##### **Motivation for or Use Case**

It clearly appears to be a bug or I'm doing something wrong ?

##### **Reproduce the error**

generate a new jhipster.net app with `jhipster --blueprints dotnetcore` and all default options
create jdl file as above
import the jdl with the command: jhipster import-jdl '.\jhipster-jdl.jdl'

##### **Related issues**

Did not find anything

##### **Suggest a Fix**

I tried to investigate the blue-print and it appears that the Relationship needs the `otherEntityRelationshipName` but I don't know how to provide it. Shouldn't it be automatically computed?

##### **JHipster Version(s)**

`npm -g list`

```
...
+-- generator-jhipster-dotnetcore@3.9.1
+-- generator-jhipster@7.9.3
...
```

##### **JHipster configuration**

`jhipster info`

```
INFO! Using bundled JHipster
INFO! No custom sharedOptions found within blueprint: generator-jhipster-dotnetcore at C:/Users/dhkf2671/AppData/Roaming/npm/node_modules/generator-jhipster-dotnetcore
INFO! No custom commands found within blueprint: generator-jhipster-dotnetcore at C:/Users/dhkf2671/AppData/Roaming/npm/node_modules/generator-jhipster-dotnetcore
(node:37940) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./lib/util/" in the "exports" field module resolution of the package at C:\Users\dhkf2671\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\package.json.
Update this package.json to use a subpath pattern like "./lib/util/*".
(Use `node --trace-deprecation ...` to show where the warning was created)

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v7.9.3

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
C:\Users\dhkf2671\source\tmp
`-- (empty)

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "applicationType": "monolith",
    "authenticationType": "jwt",
    "baseName": "Tmp",
    "blueprints": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "3.9.1"
      }
    ],
    "buildTool": "maven",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "cqrsEnabled": false,
    "creationTimestamp": 1681758639733,
    "databaseType": "sqllite",
    "devDatabaseType": "h2Disk",
    "devServerPort": 4200,
    "dtoSuffix": "DTO",
    "enableGradleEnterprise": false,
    "enableHibernateCache": true,
    "enableTranslation": true,
    "entitySuffix": "",
    "jhiPrefix": "jhi",
    "jhipsterVersion": "7.8.1",
    "languages": ["en"],
    "namespace": "Tmp",
    "nativeLanguage": "en",
    "otherModules": [
      {
        "name": "generator-jhipster-dotnetcore",
        "version": "3.9.1"
      }
    ],
    "packageName": "com.mycompany.myapp",
    "pages": [],
    "prodDatabaseType": "mysql",
    "reactive": false,
    "searchEngine": false,
    "serverPort": "5000",
    "serviceDiscoveryType": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "skipUserManagement": false,
    "testFrameworks": [],
    "websocket": false,
    "withAdminUi": true
  },
  "generator-jhipster-dotnetcore": {
    "ciType": "Github"
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Region {
	regionName String
}

entity Country {
	countryName String
}

relationship OneToOne {
	Country{region} to Region
}
</pre>
</details>


##### **Environment and Tools**

openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

git version 2.39.2.windows.1

node: v16.14.2

npm: 9.4.2

Docker version 20.10.14, build a224086

docker-compose version 1.29.2, build 5becea4c


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Folder .jhipster is empty

##### **Browsers and Operating System**

OS Name:                   Microsoft Windows 10 Entreprise
OS Version:                10.0.19043 N/A Build 19043

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by nicolas63** [comment]
Hello, everything seem good maybe link with https://github.com/jhipster/jhipster-dotnetcore/pull/1219
Can you help me to fix fix ?

**Comment by GromHub** [comment]
After downgrade, everything works as expected
Thanks for the help
