### ISSUE TITLE
[Dockerfile] Running from docker jhipster-generator-dotnetcore with error

### ISSUE THREAD

**Issue by zahasoftware** [jhipster/jhipster-dotnetcore#1336]
##### **Overview of the issue**

The error appear when I tried to regenerate the image from 0 again using command from main page of git hub

Ref:
https://github.com/jhipster/jhipster-dotnetcore#using-docker

##### **Motivation for or Use Case**

I can't generate or run the blueprint 
docker run -it --rm -v ./netcoret2:/home/jhipster/app jhipster-generator-dotnetcore

##### **Reproduce the error**
```
docker run -it --rm -v ./netcoret2:/home/jhipster/app jhipster-generator-dotnetcore
(node:1) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node:events'
Require stack:
- /usr/local/lib/node_modules/generator-jhipster/node_modules/minipass/dist/cjs/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/path-scurry/dist/cjs/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/glob/dist/cjs/src/glob.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/glob/dist/cjs/src/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/cacache/lib/util/glob.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/cacache/lib/rm.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/cacache/lib/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/pacote/lib/fetcher.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/pacote/lib/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/@npmcli/metavuln-calculator/lib/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/@npmcli/arborist/lib/audit-report.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/@npmcli/arborist/lib/arborist/audit.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/@npmcli/arborist/lib/arborist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/minipass/dist/cjs/index.js:13:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:1) UnhandledPromiseRejectionWarning: Error: Cannot find module 'node:events'
Require stack:
- /usr/local/lib/node_modules/generator-jhipster/node_modules/minipass/dist/cjs/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/path-scurry/dist/cjs/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/glob/dist/cjs/src/glob.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/glob/dist/cjs/src/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/cacache/lib/util/glob.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/cacache/lib/rm.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/cacache/lib/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/pacote/lib/fetcher.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/pacote/lib/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/@npmcli/metavuln-calculator/lib/index.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/@npmcli/arborist/lib/audit-report.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/@npmcli/arborist/lib/arborist/audit.js
- /usr/local/lib/node_modules/generator-jhipster/node_modules/@npmcli/arborist/lib/arborist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster/node_modules/minipass/dist/cjs/index.js:13:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by nicolas63** [comment]
I think the version of node in the docker image is node good, jhipster dotnet work with the version 16

**Comment by zahasoftware** [comment]
Yes the first time I get this error
<img width="265" alt="image" src="https://github.com/jhipster/jhipster-dotnetcore/assets/13983901/5b432712-de96-49fd-9352-3fb4723fe3bf">

Then I've changed to version  18.13

`
wget https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-x64.tar.gz -O /tmp/node.tar.gz 
`

But It doesn't work 

```
FROM ubuntu:20.04
RUN \
  # configure the "jhipster" user
  groupadd jhipster && \
  useradd jhipster -s /bin/bash -m -g jhipster -G sudo && \
  echo 'jhipster:jhipster' |chpasswd && \
  mkdir /home/jhipster/app && \
  export DEBIAN_FRONTEND=noninteractive && \
  export TZ=Europe\Paris && \
  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
  apt-get update && \
  # install utilities
  apt-get install -y \
    wget \
    sudo \
    git && \
  # install node.js
  wget https://nodejs.org/dist/v18.13.0/node-v18.13.0-linux-x64.tar.gz -O /tmp/node.tar.gz && \
  tar -C /usr/local --strip-components 1 -xzf /tmp/node.tar.gz && \
  # upgrade npm
  npm install -g npm && \
  # install yeoman
  npm install -g yo && \
  # cleanup
  apt-get clean && \
  rm -rf \
    /home/jhipster/.cache/ \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

RUN \
  # install jhipster
  npm install -g generator-jhipster && \
  # install the blueprint
  npm install -g generator-jhipster-dotnetcore && \
  # fix jhipster user permissions
  chown -R jhipster:jhipster \
    /home/jhipster \
    /usr/local/lib/node_modules && \
  # cleanup
  rm -rf \
    /home/jhipster/.cache/ \
    /var/lib/apt/lists/* \
    /tmp/* \
    /var/tmp/*

# expose the working directory
USER jhipster
ENV PATH $PATH:/usr/bin
WORKDIR "/home/jhipster/app"
VOLUME ["/home/jhipster/app"]
CMD ["jhipster", "--blueprints", "dotnetcore"]

```

**Comment by nicolas63** [comment]
fix with #1340

**Comment by zahasoftware** [comment]
fix with #1340, but When is it released? 

I ve tried to make a new Dockerfile, it works when I build it but when I execute it doesn't have interactive mode, could you give some tips?

And the other problem is when I try to make a volume in local folder It doesn't work too =/

```yml
# Use an official Node.js runtime as the base image
FROM node:16

# Install .NET SDK for Debian 10 (Buster)
RUN apt-get update && apt-get install -y apt-transport-https && \
    wget -q https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y dotnet-sdk-6.0

# Install JHipster globally
RUN npm install -g generator-jhipster

# Install JHipster globally
RUN npm install -g generator-jhipster-dotnetcore

# Set a working directory inside the container
WORKDIR /app

# Define a default command to run JHipster
CMD ["jhipster", "--blueprints", "dotnetcore"]
```

**Comment by nicolas63** [comment]
> fix with #1340, but When is it released? 
> 
> I ve tried to make a new Dockerfile, it works when I build it but when I execute it doesn't have interactive mode, could you give some tips?
> 
> And the other problem is when I try to make a volume in local folder It doesn't work too =/
> 
> ```yml
> # Use an official Node.js runtime as the base image
> FROM node:16
> 
> # Install .NET SDK for Debian 10 (Buster)
> RUN apt-get update && apt-get install -y apt-transport-https && \
>     wget -q https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
>     dpkg -i packages-microsoft-prod.deb && \
>     apt-get update && \
>     apt-get install -y dotnet-sdk-6.0
> 
> # Install JHipster globally
> RUN npm install -g generator-jhipster
> 
> # Install JHipster globally
> RUN npm install -g generator-jhipster-dotnetcore
> 
> # Set a working directory inside the container
> WORKDIR /app
> 
> # Define a default command to run JHipster
> CMD ["jhipster", "--blueprints", "dotnetcore"]
> ```
> 
> I execute in this way
> 
> ```bash
> docker run -it --rm -v ./test:/app node16hipster
> ```

I hope this month, but if you want test the jhipster 8 version you can swith on the branch jhipster 8 and run npm link

**Comment by zahasoftware** [comment]
I don't know how to do that, could you guide me please :(

**Comment by nicolas63** [comment]
you just need to switch on the branch jhipster 8 
`git checkout jhipster-8`
after that run 
`npm install` and `npm link`
normally after that you can execute the command jhipster-dotnetcore in an empty folder or using the dockerfile corrected with
`docker run -it --rm -v $PWD:/home/jhipster/app jhipster-generator-dotnetcore`
