### ISSUE TITLE
Debug error with blueprint 

### ISSUE THREAD

**Issue by nicolas63** [jhipster/jhipster-dotnetcore#193]
```INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-dotnetcore at C:/Users/Nicolas/AppData/Roaming/npm/node_modules/generator-jhipster-dotnetcore
INFO! Debug logging is on
INFO! No custom commands found within blueprint: generator-jhipster-dotnetcore at C:/Users/Nicolas/AppData/Roaming/npm/node_modules/generator-jhipster-dotnetcore
DEBUG!  No command specified. Running default
INFO! Running default command
DEBUG!  cmd: jhipster:app
DEBUG!  args:
DEBUG!  opts:
DEBUG!  cmdArgs:
INFO! Executing jhipster:app
INFO! Options: debug: true, skipChecks: true, skipGit: true, skipCache: true, skipInstall: true, blueprints: dotnetcore, from-cli: true, skip-checks: true, skip-git: true, skip-cache: true, skip-install: true
DEBUG! No blueprint found for blueprint generator-jhipster-dotnetcore and app subgenerator: falling back to default generator
DEBUG! Error
Error: Generator jhipster-dotnetcore:app isn't registered.
    at module.exports.composeExternalModule (D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\generators\generator-base.js:1205:19)
    at module.exports.composeBlueprint (D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\generators\generator-base-private.js:840:49)
    at D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\generators\generator-base-blueprint.js:122:49       
    at Array.forEach (<anonymous>)
    at module.exports.instantiateBlueprints (D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\generators\generator-base-blueprint.js:114:24)
    at new module.exports (D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\generators\app\index.js:244:53) 
    at Environment.instantiate (D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:674:23)
    at Environment.create (D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:637:19)
    at Environment.run (D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:725:28)
    at runYoCommand (D:\nicolas\Jhipster.Net\FORK-ME\jhipster-dotnetcore\node_modules\generator-jhipster\cli\cli.js:69:13)
DEBUG! Generator is starting


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster v6.8.0
Application files will be generated in folder: D:\tmp\debugVsCodeFolder
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

     info Using blueprint generator-jhipster-dotnetcore for server subgenerator
DEBUG! Generator is starting
DEBUG! Generator is starting


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗    ███╗   ██╗███████╗████████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗   ████╗  ██║██╔════╝╚══██╔══╝
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝   ██╔██╗ ██║█████╗     ██║
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║    ██║╚██╗██║██╔══╝     ██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗██╗██║ ╚████║███████╗   ██║
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster.NET v0.3.0
Application files will be generated in folder: D:\tmp\debugVsCodeFolder
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

? What is your default C# namespace? (MyCompany)
```

The ascii art was display twice now and error was diplay in debug mode, maybe due to your modification on blueprint auto-install @mshima ? Maybe link to https://github.com/jhipster/generator-jhipster/issues/11727 ?

**Comment by mshima** [comment]
@nicolas63 try removing the auto-install cache: `rm -rf .yo-repository`

**Comment by nicolas63** [comment]
It's the same result (i have test on an empty folder)

**Comment by mshima** [comment]
Are you trying to run a linked version?
Lookups like it's running a dotnetcore 0.3.0 instance were app blueprint doesn't exists.
`Error: Generator jhipster-dotnetcore:app isn't registered.` error is normal, it means the app blueprint was not found.

**Comment by mshima** [comment]
I think https://github.com/jhipster/generator-jhipster/issues/11727 is related to commander 3 -> 4 update.

**Comment by nicolas63** [comment]
yes, i try to run linked version

**Comment by nicolas63** [comment]
and yes in 0.3.0 the app doesn't exist but it exist now

**Comment by mshima** [comment]
See if `C:/Users/Nicolas/AppData/Roaming/npm/node_modules/generator-jhipster-dotnetcore/generators/app/index.js` exists.

**Comment by nicolas63** [comment]
Yes you're right, thanks ! i have re run npm link and the app folder appears. Now it's works !

**Comment by B-batman12thy** [comment]
For this error:"No blueprint found" you have to link the jhipster generator-blueprint to the folder you create for testing the blueprint.
