### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by robrui** [jhipster/jhipster-dotnetcore#30]
Hi!

I'm clone this repository in my machine and try to exec this blueprint with following commands:

```
git clone https://github.com/jhipster/jhipster-dotnetcore.git
ren jhipster-dotnetcore generator-jhipster-dotnetcore
cd generator-jhipster-dotnetcore
npm link
cd ..
cd myApp
npm link generator-jhipster-dotnetcore
```
In the last step, when I select one, some or all modules, I have this exception:
```
Installing languages: en for server
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at toNoCase (C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\node_modules\to-no-case\index.js:28:17)
    at toSpaceCase (C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\node_modules\to-space-case\index.js:18:10)
    at toPascalCase (C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\node_modules\to-pascal-case\index.js:18:10)
    at module.exports.configureGlobalDotnetcore (C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\generators\languages\index.js:39:43)
    at Object.<anonymous> (C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:705:18)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\Users\Roberto Ruiz\Source\Repos\generator-jhipster-dotnetcore\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```
Is sufficient data to resolve this issue? My Operating System is Windows 10.

Thanks a lot!

**Comment by danielpetisme** [comment]
Hello,

Why do you do
`ren jhipster-dotnetcore generator-jhipster-dotnetcore`, you don't need it 
Anyway I try to run the same commands on my Mac and it works but I know we had issues with the `toPascalCase` dependency these past days.
The blueprint is still experimental and moving fast so maybe we already fix the issue.
Could you:
* Update your local repo to be sure to have the latest updates (my local copy's HEAD is pointing to commit `b36a1b7`)
* give use the command you use to trigger the blueprint, (should be `jhipster --blueprint dotnetcore`)

**Comment by danielpetisme** [comment]
I spotted the issue.
The dotnet blueprint is the only JHipster blueprint to override the `LanguageGenerator` and I'm not sure why but during the `LanguageGenerator#initializing` method the property `this.baseName` is undefined.
https://github.com/jhipster/generator-jhipster/blob/52e4cec274003a4c90d2065df286f7f612a54c30/generators/languages/index.js#L109
As consequence, in the blueprint the `baseName` is undefined and trigger an error when we try to *pascalize* it...
https://github.com/jhipster/jhipster-dotnetcore/blob/master/generators/languages/index.js#L39

In order to fix the problem, I retrieve the `baseName` directly in the blueprint
https://github.com/jhipster/jhipster-dotnetcore/blob/master/generators/languages/index.js#L24
The commit: https://github.com/jhipster/jhipster-dotnetcore/commit/7613b941d2a54d207655be015dd7cdd4113b007a

**Comment by robrui** [comment]
Hi! I apologize for delayed response. Thanks for trying resolve this issue.
In last time, I has rename the folder to link _JHipster_ dependency while the package does not published in NPM.

But, I try again installing same packages (`generator-jhipster` and `generator-jhipster-dotnetcore`) and I have errors anyway when I try run the blueprint.

I attach the details below:
`jhipster --blueprints dotnetcore` (--blueprint is deprecated)
```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: The generator-jhipster-dotnetcore blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-dotnetcore.
    at Environment.error (C:\Users\Roberto Ruiz\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:176:40)
    at module.exports.error (C:\Users\Roberto Ruiz\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base.js:1448:18)
    at shelljs.exec (C:\Users\Roberto Ruiz\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base-private.js:839:22)
    at C:\Users\Roberto Ruiz\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\shelljs\src\exec.js:127:9
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
Emitted 'error' event at:
    at Environment.error (C:\Users\Roberto Ruiz\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:178:15)
    at module.exports.error (C:\Users\Roberto Ruiz\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base.js:1448:18)
    [... lines matching original stack trace ...]
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
```
I do some wrong, or the bug still already exists?

**Comment by danielpetisme** [comment]
Hello Robert,

I did a silent release of the blueprint. The version `0.1.0` is public and available but I need to work on additional documentation and communication before announce it to the world.

At the moment, we have a an issue for the entity generation. I think it's related to  the main `generator-jhipster` so I opened an issue:
https://github.com/jhipster/generator-jhipster/issues/10257
When generating an entity, jhipster is doing a sanity check to ensure the blueprint is installed. This verification relies on a system call to the `yo` package. In seems that the path produced to find the `yo` lib is wrong. he resulting error is confusing because the blueprint is actually installed is just the tool to ensure is presence which is invalid.

Anyway, we do have a workaround \o/ you should use the `--skip-checks` flag to avoid the blueprint verification.
You can check it works on this video
https://www.youtube.com/watch?v=vEcjhqbSXhg&t=115s

Since the original issue is fixed (toLowerCase undefined), could you open a new one to continue the discussion on the `blueprint not found` please.

Thank you! It's awesome to see people using the blueprint ;)

**Comment by robrui** [comment]
Thanks a lot for help about this issue!
I try with the `--skip-checks` and it works, with some errors what do not affect the local run. I'll report that in another issue.

I close the issue!
