### ISSUE TITLE
Minor: Package.json not found (wrong location) and 'rimraf' not recognized

### ISSUE THREAD

**Issue by robrui** [jhipster/jhipster-dotnetcore#33]
Hi! 
When I finish the set-up to auto-generate solution, I observe some issues in the process.

**First: The solution cannot find a package.json file**
(Console lines)
```
I'm all done. Running npm --prefix src/Enfoke install for you to install the required dependencies. If this fails, try running the command yourself.
npm ERR! code ENOLOCAL
npm ERR! Could not install from "" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rruiz\AppData\Roaming\npm-cache\_logs\2019-08-23T16_02_25_612Z-debug.log
Application successfully committed to Git.

If you find JHipster useful consider sponsoring the project https://www.jhipster.tech/sponsors/

Creating Enfoke .Net Core solution.

Client application generated successfully.
```
(Log debug file)
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--prefix',
1 verbose cli   'src/Enfoke',
1 verbose cli   'install' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose npm-session 74f4ce41e8434954
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for file: Could not install from "" as it does not contain a package.json file.
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 26ms
10 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\rruiz\Desktop\test\package.json'
11 verbose cwd C:\Users\rruiz\Desktop\test
12 verbose Windows_NT 10.0.18362
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "src/Enfoke" "install"
14 verbose node v10.16.3
15 verbose npm  v6.9.0
16 error code ENOLOCAL
17 error Could not install from "" as it does not contain a package.json file.
18 verbose exit [ 1, true ]
```

**Second: rimraf is not recognized as an internal or external command**
(Console lines)
```
> enfoke@0.0.0 cleanup C:\Users\rruiz\Desktop\test\src\Enfoke
> rimraf bin/aot && rimraf wwwroot/*

'rimraf' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! enfoke@0.0.0 cleanup: `rimraf bin/aot && rimraf wwwroot/*`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the enfoke@0.0.0 cleanup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rruiz\AppData\Roaming\npm-cache\_logs\2019-08-23T16_02_29_910Z-debug.log
INFO! Congratulations, JHipster execution is complete!
```
(Log debug file)
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--prefix',
1 verbose cli   'src/Enfoke',
1 verbose cli   'run',
1 verbose cli   'cleanup' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'precleanup', 'cleanup', 'postcleanup' ]
5 info lifecycle enfoke@0.0.0~precleanup: enfoke@0.0.0
6 info lifecycle enfoke@0.0.0~cleanup: enfoke@0.0.0
7 verbose lifecycle enfoke@0.0.0~cleanup: unsafe-perm in lifecycle true
8 verbose lifecycle enfoke@0.0.0~cleanup: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\rruiz\Desktop\test\src\Enfoke\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Users\rruiz\AppData\Local\Microsoft\WindowsApps;;C:\Users\rruiz\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\rruiz\AppData\Roaming\npm
9 verbose lifecycle enfoke@0.0.0~cleanup: CWD: C:\Users\rruiz\Desktop\test\src\Enfoke
10 silly lifecycle enfoke@0.0.0~cleanup: Args: [ '/d /s /c', 'rimraf bin/aot && rimraf wwwroot/*' ]
11 silly lifecycle enfoke@0.0.0~cleanup: Returned: code: 1  signal: null
12 info lifecycle enfoke@0.0.0~cleanup: Failed to exec cleanup script
13 verbose stack Error: enfoke@0.0.0 cleanup: `rimraf bin/aot && rimraf wwwroot/*`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid enfoke@0.0.0
15 verbose cwd C:\Users\rruiz\Desktop\test
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "--prefix" "src/Enfoke" "run" "cleanup"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error enfoke@0.0.0 cleanup: `rimraf bin/aot && rimraf wwwroot/*`
22 error Exit status 1
23 error Failed at the enfoke@0.0.0 cleanup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
Greetings!

**Comment by ivanmonteiro** [comment]
After trying variations of npm --prefix , on Windows 10, I followed [this StackOverflow thread](https://stackoverflow.com/a/57441031/552369) and could install with the following command:
`cd src\PROJECT-NAME\ && npm install && cd ..\..\`
