### ISSUE TITLE
Error when Creating Jhipster .Net Core solution.

### ISSUE THREAD

**Issue by javeez2** [jhipster/jhipster-dotnetcore#39]
`Creating Jhipster .Net Core solution.

events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: dotnet.newSln(...).then(...).catch(...).finally is not a function
    at module.exports.end (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/generators/server/index.js:176:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)`

**Comment by BananeGuimauve** [comment]
Hi ! Do you still have the error ? Have you installed the .Net Core SDK ?

**Comment by vraravam** [comment]
I get a different error:
```
Could not retrieve version of blueprint 'generator-jhipster-dotnetcore'
```

**Comment by vraravam** [comment]
I had to do the `npm link ...` part - and then it started working.

**Comment by danielpetisme** [comment]
Sounds like you solve your issue, feel free to re-open if needed
