### ISSUE TITLE
Error using entity generator

### ISSUE THREAD

**Issue by ivanmonteiro** [jhipster/jhipster-dotnetcore#46]
When running `jhipster entity author` the cli displays the field and validation questions and then the following error occurs and no entities are generated:

`
INFO! Using JHipster version installed globally
INFO! Executing jhipster:entity autor
INFO! Options: from-cli: true
     info Using blueprint generator-jhipster-dotnetcore for entity subgenerator

The entity autor is being created.

[removed questions/answers to improve readability]

events.js:174
      throw er; // Unhandled 'error' event
      ^
Error: The generator-jhipster-dotnetcore blueprint provided is not installed. Please install it using command npm i -g generator-jhipster-dotnetcore.
    at Environment.error (C:\Programas\nvm\v10.16.3\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:176:40)
    at module.exports.error (C:\Programas\nvm\v10.16.3\node_modules\generator-jhipster-dotnetcore\node_modules\generator-jhipster\generators\generator-base.js:1465:18)
    at shelljs.exec (C:\Programas\nvm\v10.16.3\node_modules\generator-jhipster-dotnetcore\node_modules\generator-jhipster\generators\generator-base-private.js:839:22)`

The error message tells me to install this generator globally, so I installed it globally again but the same error keeps happening. Is the entity generatior supported?

**Comment by ivanmonteiro** [comment]
Ended up cloning the repository and using npm link as described in the project's readme
