### ISSUE TITLE
bug:  jhipster entity <entity-name>

### ISSUE THREAD

**Issue by MrWYG** [jhipster/jhipster-dotnetcore#662]
https://jhipsternet.readthedocs.io/en/latest/Introduction/getting-started.html
When I test this Getting Started(link above), after run the order : jhipster entity
(environment: Windows 10, VS2019)
got the bug below:
• INFO! Error parsing options for generator jhipster-dotnetcore:entity, error: Error: This is a JHipster blueprint and should be used only like jhipster --blueprint dotnetcore
• ERROR! jhContext.setupEntityOptions is not a function
• TypeError: jhContext.setupEntityOptions is not a function
• at new module.exports (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster-dotnetcore\generators\entity\index.js:25:19)
• at Environment.instantiate (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:748:23)
• at Environment.create (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:720:17)
• at EntityGenerator.composeWith (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-generator\lib\index.js:1182:42)
• at EntityGenerator._composeBlueprint (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base-blueprint.js:348:37)
• at C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base-blueprint.js:248:41
• at Array.forEach ()
• at EntityGenerator.instantiateBlueprints (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\generators\generator-base-blueprint.js:247:18)
• at new EntityGenerator (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\generators\entity\index.js:147:49)
• at Environment.instantiate (C:\Users\yanguwan\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\yeoman-environment\lib\environment.js:748:23)

**Comment by nicolas63** [comment]
Which version of jhipster do you use ? 
Can you give me your .yo-rc.json (this file is in root folder) ? 
Can you try with command jhipster entity --blueprint dotnetcore ?

**Comment by MrWYG** [comment]
Jhipster 7.0.0

Use the command : jhipster entity author --blueprint dotnetcore
Result:
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-dotnetcore at C:/Users/yanguwan/AppData/Roaming/npm/node_modules/generator-jhipster-dotnetcore
INFO! No custom commands found within blueprint: generator-jhipster-dotnetcore at C:/Users/yanguwan/AppData/Roaming/npm/node_modules/generator-jhipster-dotnetcore
INFO! Error parsing options for generator jhipster-dotnetcore:entity, error: Error: This is a JHipster blueprint and should be used only like jhipster --blueprint dotnetcore
error: unknown option '--blueprint'

**Comment by MrWYG** [comment]
Can you give me your .yo-rc.json (this file is in root folder) ? where it is? I didn't find it.

**Comment by nicolas63** [comment]
sorry i have forget a s :  jhipster entity author --blueprints dotnetcore
I think you have few problems 
You use jhipster 7.0.0 but this blueprint is not yet compatible with the v7 it's in progress here (https://github.com/jhipster/jhipster-dotnetcore/pull/354)
Have you generate the application with command jhipster --blueprints dotnetcore before run jhipster entity ?

**Comment by MrWYG** [comment]
yes, I have run the command and its OK.

**Comment by MrWYG** [comment]
When I click the (http://localhost:5000/)page  'sign in', it get a exception below.

2021-03-31 10:11:55.130 EROR 24172 --- [ 36] H.M.P.ProblemDetailsMiddleware           : An unhandled exception has occurred while executing the request.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'System.String'.
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsyncInternal(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Hellang.Middleware.ProblemDetails.ProblemDetailsMiddleware.Invoke(HttpContext context)

**Comment by MrWYG** [comment]
I test the JHipster version  6.10.5 and now the command 'jhipster entity <entity-name>' is OK, thank you very much for your help.

**Comment by nicolas63** [comment]
no problem thanks for your feedbacks, the compatibility with v7 should arrive soon (this week I think)

**Comment by jeffward01** [comment]
Thanks! I also would like this fix :)
