### ISSUE TITLE
ERROR! Template file .npmrc was not found

### ISSUE THREAD

**Issue by elalejmartin** [jhipster/jhipster-dotnetcore#861]
I have the following problem when generating a project with angular on my windows 10.
If I generate it with vue or react it works fine.
Does anyone know what can happen ?
![image](https://user-images.githubusercontent.com/4900699/135728857-0115ac22-5dc6-4550-88b0-1859a209b9ac.png)

**Comment by nicolas63** [comment]
I think is due to your jhipster version can you try with jhipster 7.1.0 ? 
I will create an issue to upgrade jhipster version compatibility to 7.2.0

**Comment by damiangonzalez** [comment]
I am seeing the same issue

```
Damians-MacBook-Pro:jhipster-sample-app root# jhipster --blueprints dotnetcore
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-dotnetcore at /usr/local/lib/node_modules/generator-jhipster-dotnetcore
INFO! No custom commands found within blueprint: generator-jhipster-dotnetcore at /usr/local/lib/node_modules/generator-jhipster-dotnetcore
     info Using blueprint generator-jhipster-dotnetcore for app subgenerator


        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗    ███╗   ██╗███████╗████████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗   ████╗  ██║██╔════╝╚══██╔══╝
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝   ██╔██╗ ██║█████╗     ██║
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║    ██║╚██╗██║██╔══╝     ██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗██╗██║ ╚████║███████╗   ██║
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝

                            https://www.jhipster.tech

Welcome to JHipster.NET v3.1.1
Application files will be generated in folder: /Users/damiangonzalez/GitHub/jhipster-sample-app
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/
  If you find JHipster useful, consider sponsoring the project at https://opencollective.com/generator-jhipster
 _______________________________________________________________________________________________________________

 ______________________________________________________________________________

  JHipster update available: 7.3.0 (current: 7.1.0)

  Run npm install -g generator-jhipster to update.

 ______________________________________________________________________________

? What is the base name of your application? Jhipster
? What is your default C# namespace? Jhipster
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
     info Using blueprint generator-jhipster-dotnetcore for common subgenerator
     info Using blueprint generator-jhipster-dotnetcore for server subgenerator
     info Using blueprint generator-jhipster-dotnetcore for client subgenerator
     info Using blueprint generator-jhipster-dotnetcore for languages subgenerator
? On which port would like your server to run ? It should be unique to avoid port conflicts (choose http -> https=httpPort+1).
 5000
? Do you want to use the CQRS design pattern? No
? Which database do you want to use SQLite in-memory
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *Framework* would you like to use for the client? Angular
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? No
? Please choose the native language of the application English
? Besides JUnit and Jest, which testing frameworks would you like to use? 
? Would you like to install other generators from the JHipster Marketplace? No
ERROR! Template file .npmrc was not found at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/generators/client/templates/angular,/usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular
Error: Template file .npmrc was not found at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/generators/client/templates/angular,/usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:2209:25
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:2139:42
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:2136:29
    at Array.map (<anonymous>)
    at module.exports.writeFilesToDisk (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/generator-base.js:2135:45)
    at module.exports.writeFiles (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/generators/client/files-angular.js:521:15)
    at module.exports.writeFilesDotnetcore (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/generators/client/index.js:118:47)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-dotnetcore/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:1024:25)
Unhandled promise rejection at:
ReferenceError: /usr/local/lib/node_modules/generator-jhipster/generators/client/templates/angular/package.json.ejs:23
    21|   "name": "<%= dasherizedBaseName %>",
    22|   "version": "0.0.1-SNAPSHOT",
 >> 23|   "description": "<%= projectDescription %>",
    24|   "private": true,
    25|   "license": "UNLICENSED",
    26|   "cacheDirectories": [

projectDescription is not defined
Damians-MacBook-Pro:jhipster-sample-app root# 
```

**Comment by nicolas63** [comment]
Yes, this error is due to an incompatibility with 7.2 and 7.3 of jhipster generator the pr is in progress #865. I don't have much time at the moment but if you want to help me you are welcome

**Comment by damiangonzalez** [comment]
Thank you Nicolas for responding! I will be sure to let you know if I get enough spare time to contribute here, but unfortunately at the moment I am very pressed for time between demands at work with the family. 
   I did notice something else with my generated application however, I noticed that the docker file showed here is not part of what was generated on my machine
https://github.com/jhipster/jhipster-sample-app-dotnetcore/blob/main/src/Jhipster/Dockerfile

Do you have any idea why this may not have been included in the generated output?


On Sunday, October 17, 2021, 01:03:37 PM EDT, nicolas63 ***@***.***> wrote:  
 
 


Yes, this error is due to an incompatibility with 7.2 and 7.3 of jhipster generator the pr is in progress #865. I don't have much time at the moment but if you want to help me you are welcome

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by damiangonzalez** [comment]
> @damiangonzalez you can run docker app with ./Dockerfile-Back or use docker compose with docker-compose -f docker/app.yml up

Thank you for the feedback, yes that's exactly what I ended up doing. This command worked very well for me:
```
docker-compose -f docker/app.yml up -d
```
It was covered in the documentation I found here
https://jhipsternet.readthedocs.io/_/downloads/en/latest/pdf/
